name: Build and Release Kodi Add-on

on:
  push:
    branches:
      - master

env:
  ADDON_NAME: skin.embuary.mape

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install required tools (e.g., zip)
      - name: Install zip
        run: sudo apt-get install zip

      - name: Generate version
        id: version
        uses: codacy/git-version@2.8.0

      - name: Package add-on
        id: package
        uses: ./.github/actions/create-kodi-package
        with:
          name: ${{ env.ADDON_NAME }}
          version:  ${{ steps.version.outputs.version }}

      # Create Kodi's user data directory and copy the ZIP file there
      - name: Copy ZIP file to Kodi's addons directory
        run: |
          mkdir -p ~/.kodi/addons/packages
          cp ${{ steps.package.outputs.package-name }} ~/.kodi/addons/packages/

      # Upload the generated ZIP file as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: addon-zip
          path: ${{ steps.package.outputs.package-name }}

      # Create a Git tag
      - name: Create Tag
        id: tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      # Create a GitHub release using the generated version
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "Release ${{ steps.version.outputs.version }}"
          files: ${{ env.ADDON_NAME }}-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

